word_count/urls.py
from django.urls import path

from . import views


app_name = 'word_count'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('wordcount/', views.WordCountView.as_view(), name='api'),
    path('docs/', views.DocsView.as_view(), name='docs'),
]

word_counter_api/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('word_count.urls', namespace='wordcount')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models


class TimestampAbstractModel(models.Model):
    """Common properties among all models"""
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

word_count/forms.py
from django import forms


class WordCountForm(forms.Form):
    url = forms.URLField(
        required=True,
        label='URL',
        widget=forms.URLInput(attrs={
            'placeholder': 'Enter URL',
        })
    )
    word = forms.CharField(
        required=True,
        max_length=100,
        widget=forms.TextInput(attrs={
            'placeholder': 'Enter word',
        })
    )

word_count/views.py
import http.client as http_client

import requests
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from django.views import generic

from . import forms
from . import utils


class IndexView(generic.FormView):
    """Index page

    Contains a form that can query the API
    """
    template_name = 'word_count/index.html'
    form_class = forms.WordCountForm


class WordCountView(APIView):
    """The word count API"""
    form_class = forms.WordCountForm
    renderer_classes = (JSONRenderer,)

    def get(self, request, *args, **kwargs):
        """Count the words in the given URL

        It should be case-insensitive. If the page and word has been -
        searched, save the information to the database so it can be -
        re-used if ever it gets queried again.
        """
        # Return cache if there is
        cache = self.request.session.get(request.get_full_path_info())
        if cache:
            return Response(cache)

        form = self.form_class(request.GET)
        if form.is_valid():
            url = form.cleaned_data.get('url')
            word = form.cleaned_data.get('word')

            json = self.parse_page(url, word)

            res = Response(json)
            res.status_code = 200
            return res
        else:
            res = Response(self.render_error_response(
                message=form.errors.get_json_data(),
            ))
            res.status_code = 400  # bad request
            return res

    def parse_page(self, url, word):
        """Gets the HTML source and find all the word occurrence in it."""
        # Find the word 'fit' in the given URL
        res = requests.get(url)
        if res.status_code == 200:
            source = res.content.decode()
            word_count = utils.count_word_frequency(word, source)

            # Get JSON and save to cache
            json = self.render_ok_response(word, url, word_count)
            self.request.session[self.request.get_full_path_info()] = json

            # Set the cache expiry for an hour
            self.request.session.set_expiry(60*60)

            return self.request.session.get(self.request.get_full_path_info())
        else:
            message = http_client.responses.get(res.status_code, 500)
            res = Response(self.render_error_response(
                message=message,
            ))
            res.status_code = res.status_code
            return res

    @staticmethod
    def render_ok_response(word, url, word_count):
        """Render a successful JSON response"""
        res = {
            'status': 'ok',
            'word': word,
            'url': url,
            'word_count': word_count,
        }
        return res

    @staticmethod
    def render_error_response(message=None):
        """Render an unsuccessful JSON response"""
        res = {
            'status': 'error',
            'message': message,
        }
        return res


class DocsView(generic.TemplateView):
    template_name = 'word_count/docs.html'

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Word Frequency Counter API">
    <meta name="author" content="Erika Suzuki">

    <title>{% block title %}Word Counter API{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.1/examples/cover/cover.css" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>

<body class="text-center">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-5">
        <div class="inner">
            <h3 class="masthead-brand">Word Counter API</h3>
            <nav class="nav nav-masthead justify-content-center">
                <a class="nav-link {% block home_menu %}{% endblock %}" href="{% url 'wordcount:index' %}">Home</a>
                <a class="nav-link {% block docs_menu %}{% endblock %}" href="{% url 'wordcount:docs' %}">Docs</a>
            </nav>
        </div>
    </header>

    <main role="main">
        <div class="text-left">
            {% block content %}{% endblock %}
        </div>
    </main>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script src="{% static 'js/app.js' %}"></script>

</body>
</html>

templates/word_count/docs.html
{% extends 'base.html' %}

{% block docs_menu %}active{% endblock %}

{% block content %}
    <h3>How to use the API</h3>

    <hr>

    <p>
        Just supply the API endpoint with <code>url</code> and <code>word</code> parameters.<br />
    </p>

    <p>
        <code>url</code> should be a full URL, like <code>http://virtusize.jp</code>.
    </p>

    <p>
        <code>word</code> parameter can be anything. It can contain a alphabets and numbers.
    </p>

    <p>Your query should look like this.</p>

    <p>
        <code>https://{{ request.get_host }}/wordcount?url=http://virtusize.jp&word=fit</code>
    </p>
    

    <a href="{% url 'wordcount:api' %}?url=http://virtusize.jp&word=fit" class="btn btn-secondary" target="_blank">Try it!</a>
{% endblock %}

templates/word_count/index.html
{% extends 'base.html' %}

{% block home_menu %}active{% endblock %}

{% block content %}
    <form action="{% url 'wordcount:api' %}" method="get" class="mt-5">
        <div class="form-group">
            <input type="text" class="form-control-lg" value="http://" name="url" />
        </div>

        <div class="form-group">
            {{ form.word }}
        </div>

        <div class="form-group mt-5">
            <button type="submit" class="btn btn-primary">Count it!</button>
        </div>
    </form>
{% endblock %}